//! Derive emitter for [`WalkRevisioned`].
//!
//! Generates `impl ::revision::WalkRevisioned for T` for every
//! `#[revisioned(...)]` type whose `walk` derive flag is enabled (defaults to
//! the `deserialize` flag).
//!
//! The emitted impl is intentionally thin: structs use
//! `::revision::StructWalker` and enums use `::revision::EnumWalker`, both of
//! which expose generic positional/discriminant-based progression. The
//! derive's only job is to:
//!
//! - read the `u16` revision header,
//! - reject revisions outside the supported range,
//! - construct the correct generic walker.
//!
//! For this v1 implementation the walker only supports the **current** schema
//! revision. Callers walking older wire revisions should fall back to
//! [`DeserializeRevisioned`](::revision::DeserializeRevisioned).

use proc_macro2::TokenStream;
use quote::quote;

use crate::ast::{ItemKind, Visit};

/// Emit the [`WalkRevisioned`] impl for a `#[revisioned(...)]` item.
pub fn emit_walk_impl(
	name: &syn::Ident,
	revision: usize,
	ast: &crate::ast::Item,
) -> syn::Result<TokenStream> {
	let revision_lit = revision as u16;
	let revision_error = format!("Invalid revision `{{}}` for type `{}`", name);

	let walker_kind = match &ast.kind {
		ItemKind::Struct(_) => quote! { ::revision::StructWalker<'r, R> },
		ItemKind::Enum(_) => quote! { ::revision::EnumWalker<'r, R> },
	};

	let constructor = match &ast.kind {
		ItemKind::Struct(_) => quote! {
			Ok(::revision::StructWalker::new(reader, __revision))
		},
		ItemKind::Enum(_) => quote! {
			::revision::EnumWalker::new(reader, __revision)
		},
	};

	// Validate the wire revision matches the schema revision. v1 derive does
	// not yet support cross-revision walking; users with older payloads should
	// fall back to `DeserializeRevisioned`.
	let revision_check = quote! {
		if __revision != #revision_lit {
			return ::std::result::Result::Err(::revision::Error::Deserialize(
				::std::format!(#revision_error, __revision)
			));
		}
	};

	// Surface a `__VARIANT_NAMES` table on enums so callers can map
	// discriminants to readable names without hard-coding magic numbers.
	let variant_table = match &ast.kind {
		ItemKind::Enum(e) => emit_variant_table(name, revision, e)?,
		ItemKind::Struct(_) => quote! {},
	};

	// Surface a `__FIELD_NAMES` table on structs so callers can introspect
	// the field order at the schema revision.
	let field_table = match &ast.kind {
		ItemKind::Struct(s) => emit_struct_field_table(name, revision, s)?,
		ItemKind::Enum(_) => quote! {},
	};

	Ok(quote! {
		impl ::revision::WalkRevisioned for #name {
			type Walker<'r, R: ::std::io::Read + 'r> = #walker_kind;

			fn walk_revisioned<'r, R: ::std::io::Read>(
				reader: &'r mut R,
			) -> ::std::result::Result<Self::Walker<'r, R>, ::revision::Error> {
				let __revision = <u16 as ::revision::DeserializeRevisioned>::deserialize_revisioned(reader)?;
				#revision_check
				#constructor
			}
		}

		#variant_table
		#field_table
	})
}

/// Emit a `__VARIANT_NAMES` and `__VARIANT_DISCRIMINANT` accessor on the enum
/// so consumers can dispatch on a discriminant without hard-coding integers.
fn emit_variant_table(
	name: &syn::Ident,
	revision: usize,
	e: &crate::ast::Enum,
) -> syn::Result<TokenStream> {
	use std::collections::HashMap;

	let mut discriminants: HashMap<syn::Ident, u32> = HashMap::new();
	super::common::CalcDiscriminant::new(revision, &mut discriminants).visit_enum(e)?;

	let entries: Vec<TokenStream> = e
		.variants
		.iter()
		.filter(|v| v.attrs.options.exists_at(revision))
		.filter_map(|v| {
			let ident = &v.ident;
			let name_str = ident.to_string();
			let disc = discriminants.get(ident)?;
			Some(quote! { (#name_str, #disc) })
		})
		.collect();

	let lookup_arms: Vec<TokenStream> = e
		.variants
		.iter()
		.filter(|v| v.attrs.options.exists_at(revision))
		.filter_map(|v| {
			let ident = &v.ident;
			let name_str = ident.to_string();
			let disc = discriminants.get(ident)?;
			Some(quote! {
				#disc => ::std::option::Option::Some(#name_str),
			})
		})
		.collect();

	Ok(quote! {
		impl #name {
			/// Variant name + discriminant pairs at the current schema
			/// revision. Generated by the `revisioned` derive.
			pub const __WALK_VARIANT_TABLE: &'static [(&'static str, u32)] =
				&[#(#entries,)*];

			/// Resolve a wire discriminant to its variant name at the
			/// current schema revision, or `None` if the discriminant is
			/// unknown.
			#[inline]
			pub fn __walk_variant_name(discriminant: u32) -> ::std::option::Option<&'static str> {
				match discriminant {
					#(#lookup_arms)*
					_ => ::std::option::Option::None,
				}
			}
		}
	})
}

/// Emit a `__FIELD_NAMES` accessor on the struct so consumers can introspect
/// schema field ordering at the current revision.
fn emit_struct_field_table(
	name: &syn::Ident,
	revision: usize,
	s: &crate::ast::Struct,
) -> syn::Result<TokenStream> {
	use crate::ast::{FieldName, Fields};

	let entries: Vec<TokenStream> = match &s.fields {
		Fields::Named {
			fields,
			..
		} => fields
			.iter()
			.filter(|f| f.attrs.options.exists_at(revision))
			.map(|f| {
				let lit = match &f.name {
					FieldName::Ident(i) => i.to_string(),
					FieldName::Index(i) => i.index.to_string(),
				};
				quote! { #lit }
			})
			.collect(),
		Fields::Unnamed {
			fields,
			..
		} => fields
			.iter()
			.filter(|f| f.attrs.options.exists_at(revision))
			.enumerate()
			.map(|(idx, _)| {
				let lit = idx.to_string();
				quote! { #lit }
			})
			.collect(),
		Fields::Unit => Vec::new(),
	};

	Ok(quote! {
		impl #name {
			/// Field names at the current schema revision in wire order.
			/// Generated by the `revisioned` derive.
			pub const __WALK_FIELD_NAMES: &'static [&'static str] =
				&[#(#entries,)*];
		}
	})
}
